[package]
name = "spaceman"
version = "0.1.2"
edition = "2021"

[dependencies]
get_sys_info = "0.1.21"
gtk = { version = "0.6", package = "gtk4", features = ["v4_6"] }
jwalk = "0.5"
once_cell = "1.17.1"
